### ISSUE TITLE
Doesn't work (js errors) in IE 7, 8, 9

### ISSUE THREAD

**Issue by carasmo** [frankdejonge/Simple-Javascript-Loader#1]
Unfortunately, I have to make this site work in these crap ass browsers? Any suggestions on how to make it work, should I load the scripts differently?

**Comment by frankdejonge** [comment]
Hey @carasmo, can you supply a little more info? Is there anything in the debugger? Then I'll know what to look for. Spreading the word is more then enough to thank me. Coded this up in about an hour.

**Comment by frankdejonge** [comment]
Closing due to lack of response.
