### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by aggregat4** [frankdejonge/Simple-Javascript-Loader#2]
As far as I can tell this (very useful) library has no license specified. This makes it hard to reuse it in any real contexts. Could you create a LICENSE file to identify the license?

Once you decide on a license using http://choosealicense.com/ , you can automate adding it using http://www.addalicense.com/ .

**Comment by frankdejonge** [comment]
@aggregat4 the licence is MIT, I'll add it.

**Comment by aggregat4** [comment]
Fantastic! Simple Javascript Loader is just what we need BTW, the nice .seq() syntax makes it easy to migrate from our legacy straightforward sequential file loading and to start optimizing piece by piece.
